

CREATE USER C##EUCEDA7 IDENTIFIED BY CEUCEDA;
alter session set "_oracle_script"=true;
CREATE USER CEUCEDA8 IDENTIFIED BY CEUCEDA;

GRANT CONNECT, RESOURCE, dba TO CEUCEDA8;
GRANT UNLIMITED TABLESPACE TO CEUCEDA8;

ALTER PROFILE DEFAULT LIMIT PASSWORD_REUSE_TIME UNLIMITED;
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;

-- REVOKE
-- DROP USER CEUCEDA CASCADE;


CREATE ROLE DESARROLLADOR;
GRANT CREATE SESSION, CREATE TABLE, ALTER ANY TABLE, DROP ANY TABLE,
INSERT ANY TABLE, UPDATE ANY TABLE, DELETE ANY TABLE, SELECT ANY TABLE
TO DESARROLLADOR

SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE = 'DESARROLLADOR';

GRANT DESARROLLADOR TO CEUCEDA

